# Generated by Django 3.2.12 on 2024-06-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShareDocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='sharedocs_comment',
        ),
        migrations.AlterModelTable(
            name='file',
            table='sharedocs_file',
        ),
        migrations.AlterModelTable(
            name='user',
            table='sharedocs_user',
        ),
    ]
