# Generated by Django 3.2.12 on 2024-06-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShareDocs', '0002_auto_20240614_1800'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='file',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
